### ISSUE TITLE
outbreaker_data adds values <1e-15 to w_dens (while it should not)

### ISSUE THREAD

**Issue by PascalCrepey** [reconhub/outbreaker2#36]
Hi, 
when w_dens is shorter than the range of inputed dates, outbreaker_data adds an exponential tail to w_dens standing for 1e-4. However as soon as you have to add more than 25 values, the last values of the tail go below 1e-15 which triggers a warning afterwards (when outbreaker_data is run a second time from outbreaker).
I don't know whether the 1e-15 limit is real or if it can safely be replaced by ==0, what is sure is that this limit will not be respected for large dataset, where length(w_dens) will very often be shorter than max_range... I would suggest at least changing line 107 to: 
```R 
data$w_dens <- c(data$w_dens, val_to_add[which(val_to_add>=1e-15)])
```

Pascal

**Comment by thibautjombart** [comment]
Many thanks for spotting this! This tail is needed to avoid that star-like
tree initialisation results in a -Inf log-likelihood. I will tweak it to
allow for longer tails.
