### ISSUE TITLE
Segfault on Travis

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/outbreaker2#39]
Travis currently fails:
https://travis-ci.org/reconhub/outbreaker2/builds/252440203?utm_source=email&utm_medium=notification

Apparently a segfault during the tests? Not sure what's going on.. local checks are fine on my side.

**Comment by thibautjombart** [comment]
I'm also seeing a bunch of local changes akin to what you were mentioning @finlaycampbell ; see 244ee254c25258ab97026160fa435c3161601716

**Comment by finlaycampbell** [comment]
Seems to be building after your latest commit updating the Rcpp exports? I'm not sure exactly what's going on, but I had errors compiling outbreaker at times, and it had something to do with the changes in Rcpp exports - hopefully it's fixed now and won't crop up again?

**Comment by thibautjombart** [comment]
Yep, there's weird stuff happening every now and then on Travis.. let's hope it's okay!
