### ISSUE TITLE
seqTrack initialisation fails with partial dna sampling

### ISSUE THREAD

**Issue by finlaycampbell** [reconhub/outbreaker2#42]
seqTrack initialisation currently assumes all cases have dna sequences and fails when this is not the case - either we should use seqTrack initialisation only when are cases have dna sequences, or modify the initialisation so that it works with partial dna sampling

**Comment by thibautjombart** [comment]
Good point. seqTrack is not defined for missing sequences, so I would just generate an error just like when there are no DNA sequences; see:
https://github.com/reconhub/outbreaker2/blob/master/R/create_config.R#L582

I won't make the change, currently travelling and workshopping and don't want to risk breaking things. @finlaycampbell would you mind making the change?

**Comment by finlaycampbell** [comment]
This was fixed a while ago, closing now
