### ISSUE TITLE
Converging to lower log-post with time only

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/outbreaker2#47]
I have just seen this when working on the Ebola practical for Epidemics;when using time only for some random seeds I get:

![image](https://user-images.githubusercontent.com/10757154/33182670-e0245674-d06c-11e7-9996-54c3e29173e5.png)

I will post some reproducible code when I have time. The posterior trees seem fine, they are well explored. Only unusual thing I can think of here is that the imported case changes quite often, so there are moving NAs in kappas.

**Comment by thibautjombart** [comment]
Haha, @finlaycampbell this is a good news. I was using the old version. =D

**Comment by finlaycampbell** [comment]
Phew, was not looking forward to another bug hunt!

**Comment by thibautjombart** [comment]
Yeah I bet ;)
