### ISSUE TITLE
Change network figure settings for publication

### ISSUE THREAD

**Issue by r0sies** [reconhub/outbreaker2#73]
Hi,
I have created the interactive network diagram with outbreaker2 and would like to change the font size of the labels (or increase the viewer height, width canvas size) so that I can export the resulting (non-interactive) diagram to a PNG/TIFF/JPG for a manuscript. Do you have suggestions for how I can achieve this? Thank you, Rosie

**Comment by finlaycampbell** [comment]
Hi,
We haven't implemented these options within outbreaker2 but you can modify the plot object that is outputted quite easily, as follows:
```
library(visNetwork)
library(magrittr)
p <- plot(x, type = 'network') %>%
  visNodes(font = list(size = 20))
p$width  <- 1000
p$height <- 1000
```
You can then right-click on the dynamic image (opened in a browser) and save it. Let me know if this answers your question!
