### ISSUE TITLE
outbreaker_data dates as.numeric

### ISSUE THREAD

**Issue by CyGei** [reconhub/outbreaker2#81]
Hi,

Although the documentation states that dates should be provided as "Dates" or as "integers", one can still submit a numeric vector but outbreaker2 will not warn the user.

Looking at outbreaker_data.R, it seems that it will first round the numeric values before converting to integers. Therefore if someone provides dates as c(1, 1.5, 2), outbreaker will convert to c(1, 2, 2) without warnings.  Should that be modified?

@thibautjombart

**Comment by finlaycampbell** [comment]
Now fixed with merge.
