### ISSUE TITLE
Equation for corrected genetic likelihood in README

### ISSUE THREAD

**Issue by javierps** [reconhub/outbreaker2#87]
Hello,

I suppose there is a typo in the corrected genetic likelihood in the homepage's README which does not match the equation given in Campbell et al. (2019) https://doi.org/10.1371/journal.pcbi.1006930.

If I understood correctly, the equation should read:

`(kappa*mu)^d(s_i,s_alpha_i)(1-kappa*mu)^(l(s_i,s_alpha_i)-d(s_i,s_alpha_i))`

Javier

**Comment by finlaycampbell** [comment]
Hi Javier - so sorry for never responding to this issue, I must have missed it at the time and am not really tracking this repo on the regular. Issue now fixed in 672541efe4926352de5781c47432746d717b9832 :)
